### ISSUE TITLE
Error in field referencing

### ISSUE THREAD

**Issue by SpheMakh** [bennahugo/politsiyakat#7]
```
politsiyakat - INFO 2018-01-22 19:31:24,120:	Updating flags for chunk 11 of 406...
politsiyakat - INFO 2018-01-22 19:31:24,122:		Reading MS
politsiyakat - INFO 2018-01-22 19:31:24,122:		Selecting field PKS1934-63...
politsiyakat - INFO 2018-01-22 19:31:24,459:	Waiting for remaining jobs to finish...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__main__.py", line 25, in <module>
    politsiyakat.main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__init__.py", line 129, in main
    run_func(**args.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/modules/flag_tasks.py", line 401, in flag_phase_drifts
    flgs = new_flags[field_id][s].copy()
KeyError: 4
```

**Comment by KshitijT** [comment]
Ditto for me.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__main__.py", line 25, in <module>
    politsiyakat.main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/__init__.py", line 129, in main
    run_func(**args.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/politsiyakat/modules/flag_tasks.py", line 401, in flag_phase_drifts
    flgs = new_flags[field_id][s].copy()
```
